name: Train Gomoku AI Model

on:
  push:
    branches:
      - main # Triggers the workflow on push events to the main branch
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Prepare data using your script
      id: prepare_data
      run: python process_sgf.py
      working-directory: ./data

    - name: Train the model
      id: train_model
      run: python train.py

    - name: Upload Model as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: gomoku-model
        path: gomoku_model.onnx
